ALTER TABLE ORDERS
ADD CONSTRAINT fk_orders_user
FOREIGN KEY (USERID)
REFERENCES USERBASE(USERID);

ALTER TABLE REVIEWS
ADD CONSTRAINT fk_reviews_user
FOREIGN KEY (USERID)
REFERENCES USERBASE(USERID);

ALTER TABLE REVIEWS
ADD CONSTRAINT fk_reviews_product
FOREIGN KEY (PRODUCTCODE)
REFERENCES PRODUCTS(PRODUCTCODE);

ALTER TABLE USERLIBRARY
ADD CONSTRAINT fk_userlibrary_user
FOREIGN KEY (USERID)
REFERENCES USERBASE(USERID);

ALTER TABLE USERLIBRARY
ADD CONSTRAINT fk_userlibrary_product
FOREIGN KEY (PRODUCTCODE)
REFERENCES PRODUCTS(PRODUCTCODE);

SELECT FIRSTNAME || ' ' || LASTNAME AS FULLNAME,
       USERNAME
FROM USERBASE
WHERE FLOOR(MONTHS_BETWEEN(SYSDATE, DATEOFBIRTH)/12) >= 18;

SELECT MAX(LENGTH(USERNAME)) AS MAX_LENGTH,
       AVG(LENGTH(USERNAME)) AS AVG_LENGTH
FROM USERBASE;

SELECT QUESTION
FROM SECURITYQUESTION
WHERE QUESTION LIKE 'What is%'
   OR QUESTION LIKE 'What was%';

SELECT PRODUCTCODE,
       MIN(RATING) AS LOWEST_RATING,
       COUNT(*) AS REVIEW_COUNT
FROM REVIEWS
GROUP BY PRODUCTCODE
ORDER BY REVIEW_COUNT DESC;

SELECT PRODUCTCODE,
       COUNT(*) AS USER_COUNT
FROM WISHLIST
WHERE POSITION = 1
GROUP BY PRODUCTCODE;

SELECT USERID,
       SUM(TOTALAMOUNT) AS TOTAL_SPENT
FROM ORDERS
GROUP BY USERID;

SELECT PURCHASEDATE,
       SUM(TOTALAMOUNT) AS DAILY_PROFIT
FROM ORDERS
GROUP BY PURCHASEDATE
ORDER BY DAILY_PROFIT DESC;

SELECT *
FROM (
    SELECT PRODUCTCODE,
           SUM(HOURSPLAYED) AS TOTAL_HOURS
    FROM USERLIBRARY
    GROUP BY PRODUCTCODE
    ORDER BY TOTAL_HOURS DESC
)
WHERE ROWNUM <= 5;

CREATE VIEW user_infraction_count AS
SELECT USERID,
       COUNT(*) AS INFRACTION_COUNT
FROM INFRACTIONS
GROUP BY USERID
ORDER BY INFRACTION_COUNT DESC;

CREATE VIEW user_rule_breaks AS
SELECT USERID,
       RULENUM,
       COUNT(*) AS TIMES_BROKEN
FROM INFRACTIONS
GROUP BY USERID, RULENUM
ORDER BY USERID;

SELECT RULENUM,
       PENALTY,
       COUNT(*) AS PENALTY_COUNT
FROM INFRACTIONS
GROUP BY RULENUM, PENALTY;

SELECT AVG(DATEUPDATED - DATESUBMITTED) AS AVG_TIME,
       MAX(DATEUPDATED - DATESUBMITTED) AS MAX_TIME,
       MIN(DATEUPDATED - DATESUBMITTED) AS MIN_TIME
FROM TICKETS
WHERE STATUS = 'CLOSED';

SELECT EMAIL,
       ISSUE,
       COUNT(*) AS ISSUE_COUNT
FROM TICKETS
WHERE STATUS = 'NEW'
GROUP BY EMAIL, ISSUE, DATESUBMITTED
ORDER BY ISSUE_COUNT DESC;

SELECT USERID, USERNAME
FROM USERBASE
WHERE LOWER(PASSWORD) LIKE '%' || LOWER(FIRSTNAME) || '%'
   OR LOWER(PASSWORD) LIKE '%' || LOWER(LASTNAME) || '%';

SELECT PUBLISHER,
       AVG(PRICE) AS AVG_PRICE
FROM PRODUCTS
GROUP BY PUBLISHER
ORDER BY PUBLISHER;

CREATE VIEW discounted_products AS
SELECT PRODUCTNAME,
       PRICE * 0.75 AS DISCOUNT_PRICE
FROM PRODUCTS
WHERE RELEASEDATE < ADD_MONTHS(SYSDATE, -60);

SELECT GENRE,
       MAX(PRICE) AS MAX_PRICE,
       MIN(PRICE) AS MIN_PRICE
FROM PRODUCTS
GROUP BY GENRE;

CREATE VIEW recent_chatlog AS
SELECT *
FROM CHATLOG
WHERE DATESENT BETWEEN SYSDATE - 7 AND SYSDATE;

CREATE VIEW recent_penalties AS
SELECT USERID,
       DATEASSIGNED,
       PENALTY
FROM INFRACTIONS
WHERE PENALTY IS NOT NULL
  AND DATEASSIGNED >= ADD_MONTHS(SYSDATE, -1);
