--AUBREY- QUESTION 1
SELECT u.USERID
FROM USERBASE u
WHERE u.USERID NOT IN (
    SELECT o.USERID FROM ORDERS o
);

--AUBREY- QUESTION 2
SELECT p.PRODUCTCODE
FROM PRODUCTLIST p
WHERE p.PRODUCTCODE NOT IN (
    SELECT r.PRODUCTCODE FROM REVIEWS r
);

--AUBREY- QUESTION 3
SELECT u.*,
       CASE 
           WHEN TRUNC(MONTHS_BETWEEN(SYSDATE, u.BIRTHDAY)/12) >= 18 THEN 'Adult'
           ELSE 'Minor'
       END AS AGE_GROUP

--AUBREY- QUESTION 4
SELECT p.*,
       CASE 
           WHEN p.PRICE <= 20 THEN 'On Sale'
           ELSE 'Base Price'
       END AS PRICE_LABEL
FROM PRODUCTLIST p;

--AUBREY- QUESTION 5
SELECT ul.USERID
FROM USERLIBRARY ul
JOIN USERPROFILE up ON ul.USERID = up.USERID
WHERE ul.PRODUCTCODE = 'GAME6'
AND up.IMAGEFILE IS NOT NULL;

--AUBREY- QUESTION 6
SELECT DISTINCT w.PRODUCTCODE
FROM WISHLIST w
JOIN REVIEWS r ON w.PRODUCTCODE = r.PRODUCTCODE
WHERE w.POSITION IN (1,2)
AND r.RATING >= 3;

--AUBREY- QUESTION 7
SELECT u1.USERNAME, u1.BIRTHDAY
FROM USERBASE u1
JOIN USERBASE u2 
ON u1.BIRTHDAY = u2.BIRTHDAY
AND u1.USERID <> u2.USERID;

--AUBREY- QUESTION 8
SELECT *
FROM USERLIBRARY ul
CROSS JOIN WISHLIST w;

--AUBREY- QUESTION 9
SELECT TO_CHAR(USERID) AS ID, USERNAME AS NAME
FROM USERBASE
UNION ALL
SELECT PRODUCTCODE AS ID, PRODUCTNAME AS NAME
FROM PRODUCTLIST;

--AUBREY- QUESTION 10
SELECT CHATID, CONTENT AS ACTIVITY, DATESENT
FROM CHATLOG
UNION ALL
SELECT USERID, TO_CHAR(IMAGEFILE), NULL
FROM USERPROFILE;

--AUBREY- QUESTION 11
SELECT u.USERNAME
FROM USERBASE u
WHERE u.USERID NOT IN (
    SELECT i.USERID FROM INFRACTIONS i
);

--AUBREY- QUESTION 12
SELECT c.TITLE, c.DESCRIPTION
FROM COMMUNITYRULES c
WHERE c.RULENUM NOT IN (
    SELECT i.RULENUM FROM INFRACTIONS i
);

--AUBREY- QUESTION 13
SELECT u.USERNAME, u.EMAIL
FROM USERBASE u
JOIN INFRACTIONS i ON u.USERID = i.USERID
WHERE i.PENALTY IS NOT NULL;

--AUBREY- QUESTION 14
SELECT i.DATEASSIGNED
FROM INFRACTIONS i
JOIN USERSUPPORT us 
ON TRUNC(i.DATEASSIGNED) = TRUNC(us.DATESUBMITTED);

--AUBREY- QUESTION 15
SELECT TITLE, DESCRIPTION
FROM COMMUNITYRULES;

--AUBREY- QUESTION 16
SELECT c.*,
       CASE 
           WHEN c.SEVERITYPOINT >= 10 THEN 'Bannable'
           ELSE 'Appealable'
       END AS RULE_TYPE
FROM COMMUNITYRULES c;

--AUBREY- QUESTION 17
SELECT us.*,
       CASE 
           WHEN us.STATUS <> 'CLOSED'
           AND us.DATEUPDATED < SYSDATE - 7 THEN 'High Priority'
           ELSE 'Normal'
       END AS PRIORITY
FROM USERSUPPORT us;

--AUBREY- QUESTION 18
SELECT *
FROM USERSUPPORT us
CROSS JOIN INFRACTIONS i;

--AUBREY- QUESTION 19
SELECT TICKETID, DATEUPDATED
FROM USERSUPPORT
WHERE STATUS = 'CLOSED'
AND TRUNC(DATEUPDATED) = TRUNC(DATEUPDATED);

--AUBREY- QUESTION 20
SELECT USERID, 'USER' AS TYPE
FROM USERBASE
UNION ALL
SELECT USERID, 'INFRACTION' AS TYPE
FROM INFRACTIONS;
